services:
  jenkins:
    #jenkins/jenkins:lts 이미지를 사용
    image: jenkins/jenkins:lts
    #컨테이너 이름 설정
    container_name: jenkins
    user: root
    privileged: true
    #jenkins 접속 port -p
    ports:
      - 8080:8080
      - 50000:50000
    #jenkins 볼룸 설정 -v
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins: